### ISSUE TITLE
Feature 1- User Can Search A Card

### ISSUE THREAD

**Issue by NCFern** [NCFern/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a card by name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create an interactive search feature that can search for a card by its full or partial name. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-02 at 10 11 11 AM](https://user-images.githubusercontent.com/99868725/182434113-180ac656-f40c-46cd-a63f-857bffce03dd.png)
![Screen Shot 2022-08-02 at 10 11 24 AM](https://user-images.githubusercontent.com/99868725/182434119-69da0ed8-2abf-4da0-8a9d-261639ae7463.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build basic HTML/CSS structure according to Figma
- [x] Add a div[data-view="search"] to the HTML
- [x] Add a search input and submit button to the HTML
- [x] Make the search input required for submitting 
- [x] Add an empty div[id="search-results"] to the HTML
- [x] Listen for 'submit' events on the submit button and:
  - [x] Make an API request for the name searched
  - [x] If there is no card, return a 'no match screen'
- [x] Create a DOM element that displays the card name and its variants (column-fifth in desktop, column- half in mobile)
  - [x] Add a resultId to each displayed card
  - [x] Increment the resultID property in the data model
- [x] Append  the new searched DOM elements to the empty div[id="search-results"]
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
