### ISSUE TITLE
Feature: User can View Card Details

### ISSUE THREAD

**Issue by NCFern** [NCFern/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a specific card.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks a card, they can view the card's name, set, rarity, and online pricing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-08-12 at 4 40 43 PM](https://user-images.githubusercontent.com/99868725/184457235-2bf99015-2619-4549-b8c1-5c6cd5d76da2.png)
![Screen Shot 2022-08-12 at 4 40 56 PM](https://user-images.githubusercontent.com/99868725/184457239-38d48cdd-fe74-4b93-b660-d1775cc36870.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a div[data-view: details] in the html
- [x] In JS, create a function that can swap between 'search results' and 'card details'
- [x] Create click event listeners for each of the results
- [x] Design 'card details' layout in HTML
- [x] Create a button that listens for clicks that swaps from 'card details' to 'search results'
- [x] Make a variable that contains the value of xhr response of the card's name, set, and price
- [x] Display that data alongside the associated card image in 'card details'
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
