### ISSUE TITLE
Feature 3: User can Favorite A Card

### ISSUE THREAD

**Issue by NCFern** [NCFern/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can favorite a card they select.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the heart icon associated with the card, turns and stays a different color.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-08-18 at 11 37 00 AM](https://user-images.githubusercontent.com/99868725/185469573-a3953d6d-dcb1-424e-b79d-ab421139841d.png)
![Screen Shot 2022-08-18 at 11 37 23 AM](https://user-images.githubusercontent.com/99868725/185469581-f478576e-83e2-455e-9922-b20b41a76d81.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make a Heart Icon on the HTML inside div[data-view" details]
- [x] Have the Heart Icon listen for clicks and when it is clicked, it turns and stays a different color
- [x] Have a function that adds the selected card's data into local storage once the heart is clicked
- [ ] Ensure that data is saved into local storage
- [ ] Ensure that each card in the data model is assigned a card-id
- [ ] Make sure each card-id gets incremented as you add more cards
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
